version: "3.9"
services:
  prometheus:
    #network_mode: host
    # networks:
      # - consul
    # dns: dev-consul-server      
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
      - ./data/prometheus/data:/prometheus
  #  command:
  #    - '-config.file=/etc/prometheus/prometheus.yml'
  #    - '-storage.local.path=/prometheus'
  #    - '-alertmanager.url=http://alertmanager:9093'
    expose:
      - 9090
    ports:
      - 9090:9090
    # links:
      # - dev-consul-server:dev-consul-server
  #    - cadvisor:cadvisor
  #    - node-exporter:node-exporter
  #    - alert-manager:alert-manager

  dev-consul-server:
    #network_mode: host
    # networks:
      # - consul
    # dns: dev-consul-server
    image: consul:latest
    container_name: dev-consul-server
    restart: unless-stopped
    expose:
      - 8600/udp
      - 8500
      - 8400
      - 8300
    ports: 
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    volumes: 
      - ./consul.d/:/consul/config:rw
    environment: 
      - CONSUL_BOOTSTRAP_EXPECT=3
      - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0
      - CONSUL_DISABLE_KEYRING_FILE=true
      - CONSUL_RETRY_JOIN=dev-consul-server
    command: [ "consul", "agent", "-bootstrap-expect=1", "-server", "-data-dir=/consul/data", "-bind={{ GetInterfaceIP \"eth0\" }}", "-client=0.0.0.0", "-ui"]

  #dev-consul-client:
  #  image: consul:latest
  #  container_name: dev-consul-client
  #  restart: unless-stopped
  #  command: "agent -node=client-1 -join=dev-consul-server"
  #  links:
  #  - dev-consul-server:dev-consul-server

  alert-manager:
    #network_mode: host    
    # networks:
      # - consul
    # dns: dev-consul-server      
    image: prom/alertmanager:latest
    container_name: alert-manager
    ports:
      - 9093:9093
  #  networks:
  #    - public
  #  command:
  #    - '--log.level=debug'
    volumes:
  #    - ./data/alertmanager/config/prometheus-config.yml:/fragments/alertmanager-server.yml
      #- ./data/alertmanager/alerts.json:/etc/prometheus/targets/alertmanager.json
      - ./data/alertmanager/alertmanager.yml:/alertmanager.yml
    # links:
      # - dev-consul-server:dev-consul-server      
    command: ["--config.file=/alertmanager.yml"]

  node-exporter:
    #network_mode: host    
    # networks:
      # - consul
    # dns: dev-consul-server      
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    expose:
      - 9100
    ports:
      - 9100:9100
    # links:
      # - dev-consul-server:dev-consul-server      

  cadvisor:
    #network_mode: host    
    image: google/cadvisor:latest
    # networks:
      # - consul
    # dns: dev-consul-server      
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080
    ports: 
      - 8080:8080
    # links:
      # - dev-consul-server:dev-consul-server      
    
  grafana:
    #network_mode: host    
    image: grafana/grafana:latest
    # networks:
      # - consul
    # dns: dev-consul-server
    container_name: grafana
    restart: unless-stopped
    # links:
      # - prometheus:prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana:rw
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=ifcspassword
      - GF_USERS_ALLOW_SIGN_UP=false
  #      - GF_SERVER_DOMAIN=localhost
  #      - GF_SMTP_ENABLED=true
  #      - GF_SMTP_HOST=smtp.gmail.com:587
  #      - GF_SMTP_USER=myadrress@gmail.com
  #      - GF_SMTP_PASSWORD=mypassword
  #      - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com
    # links:
    # - dev-consul-server:dev-consul-server

# networks:
  # consul: